# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 98f74b1f51a01d02c0cec61547f984bf27fe927d9d67b49f44b731900950ae00e2e461c8cc8cf83b22ea651d45922f93c935e5545a7e341c334c06669027e42d

test:
  secret_key_base: b969b254a5247dba7415ef950bfb3eae9262943dd2800d6f41b443814ee96cf1873f50436f1c85d6254130e801e9b5df28019b8144a29b1183d68b89884227d9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
